/** Drizzle schema for the LiftOff database.
 *
 * Hand-written from the live Supabase schema captured on 2026-08-03
 * (information_schema.columns + the foreign-key graph + pg_get_viewdef).
 * This file is the source of truth for the schema.
 *
 * NOT generated by `drizzle-kit pull`, deliberately. Introspection would have
 * faithfully carried over the Supabase-isms that must NOT come with us:
 *
 *  - `users.id DEFAULT auth.uid()` — auth.uid() is a Supabase function and does
 *    not exist in RDS. Ids now come from the verified JWT `sub`.
 *  - `users.email NOT NULL` with nothing in the app writing it — a trigger on
 *    auth.users populated it at signup. That trigger does not come with us
 *    either, so the API owns row creation on first login.
 *  - `athletes.id` / `coaches.id` had `DEFAULT gen_random_uuid()` despite always
 *    being the user's id. Vestigial and actively misleading; dropped.
 *
 * The five views are NOT modelled here — Drizzle does not do views, and they
 * port unchanged as plain SQL because none of them reference auth.uid().
 * See migration 0001_create_views.sql.
 */

import {
  bigint,
  boolean,
  date,
  doublePrecision,
  index,
  integer,
  pgEnum,
  pgTable,
  smallint,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';

// ---------------------------------------------------------------------------
// Enums
//
// The column dump reported these only as USER-DEFINED, so the type names and
// value lists were recovered separately.
// ALL FOUR VERIFIED 2026-08-04 against the live project, read out of the
// PostgREST OpenAPI spec (which enumerates enum-typed columns) rather than
// guessed. The reconstruction was right on three; coach_athlete_relationship_status
// had a speculative 'inactive' that does not exist and has been removed.
// ---------------------------------------------------------------------------

export const genderEnum = pgEnum('gender', ['Male', 'Female', 'Gender-fluid']);

export const coachRequestStatusEnum = pgEnum('coach_request_status', [
  'pending',
  'accepted',
  'rejected',
]);

export const coachAthleteRelationshipStatusEnum = pgEnum('coach_athlete_relationship_status', [
  'pending',
  'active',
]);

export const messageTypeEnum = pgEnum('message_type', ['text', 'image', 'video', 'file']);

// ---------------------------------------------------------------------------
// Identity
// ---------------------------------------------------------------------------

/** The profile row. One per Supabase auth user.
 *
 * `id` matches the Supabase `auth.users.id` but there is no longer a foreign key
 * to it — auth lives in a different database now. Nothing at the database level
 * prevents an orphaned profile; the API is responsible for creating this row on
 * first login and for not leaving strays behind.
 */
export const users = pgTable('users', {
  id: uuid('id').primaryKey(),
  username: text('username').unique(),
  email: text('email').notNull(),
  gender: genderEnum('gender'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  dateOfBirth: date('date_of_birth'),
  firstName: text('first_name'),
  lastName: text('last_name'),
  isAthlete: boolean('is_athlete'),
  isCoach: boolean('is_coach'),
  avatarUrl: text('avatar_url'),
});

/** Placeholder for unbuilt team features. Two columns, no rows written by
 * anything. Carried over only because athletes.team_id references it. */
export const teams = pgTable('teams', {
  id: uuid('id').primaryKey(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const federations = pgTable('federations', {
  id: uuid('id').primaryKey().defaultRandom(),
  code: text('code').notNull(),
  name: text('name'),
});

export const divisions = pgTable('divisions', {
  id: uuid('id').primaryKey().defaultRandom(),
  federationId: uuid('federation_id')
    .notNull()
    .references(() => federations.id),
  name: text('name'),
  minimumAge: integer('minimum_age'),
  maximumAge: integer('maximum_age'),
});

export const weightClasses = pgTable('weight_classes', {
  id: uuid('id').primaryKey().defaultRandom(),
  federationId: uuid('federation_id')
    .notNull()
    .references(() => federations.id),
  gender: genderEnum('gender'),
  name: text('name'),
  minWeight: doublePrecision('min_weight'),
  maxWeight: doublePrecision('max_weight'),
  sortOrder: smallint('sort_order'),
  active: boolean('active'),
});

/** `id` is both primary key and foreign key to users — athlete id IS user id. */
export const athletes = pgTable('athletes', {
  id: uuid('id')
    .primaryKey()
    .references(() => users.id),
  federationId: uuid('federation_id').references(() => federations.id),
  divisionId: uuid('division_id').references(() => divisions.id),
  weightClassId: uuid('weight_class_id').references(() => weightClasses.id),
  teamId: uuid('team_id').references(() => teams.id),
});

export const coaches = pgTable('coaches', {
  id: uuid('id')
    .primaryKey()
    .references(() => users.id),
  biography: text('biography'),
  yearsOfExperience: integer('years_of_experience'),
});

// ---------------------------------------------------------------------------
// Coach <-> athlete
// ---------------------------------------------------------------------------

export const coachRequests = pgTable(
  'coach_requests',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }),
    athleteId: uuid('athlete_id')
      .notNull()
      .references(() => athletes.id),
    coachId: uuid('coach_id')
      .notNull()
      .references(() => coaches.id),
    status: coachRequestStatusEnum('status').default('pending'),
  },
  (table) => [
    // Both directions are read: an athlete lists invitations addressed to them,
    // a coach lists the ones they sent.
    index('coach_requests_athlete_id_idx').on(table.athleteId),
    index('coach_requests_coach_id_idx').on(table.coachId),
  ],
);

export const coachAthleteRelationships = pgTable(
  'coach_athlete_relationships',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    athleteId: uuid('athlete_id')
      .notNull()
      .references(() => athletes.id),
    coachId: uuid('coach_id')
      .notNull()
      .references(() => coaches.id),
    status: coachAthleteRelationshipStatusEnum('status').notNull().default('pending'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index('coach_athlete_relationships_athlete_id_idx').on(table.athleteId),
    index('coach_athlete_relationships_coach_id_idx').on(table.coachId),
    /** Nothing prevented a duplicate pair before this, and with 3 coaches
     * re-inviting across a 50-athlete roster it was a matter of time.
     *
     * Deliberately on the PAIR, not on athlete_id alone: this forbids the same
     * coach being linked to the same athlete twice, while leaving open whether an
     * athlete may have two *different* coaches. That question is still undecided
     * (docs/ROADMAP.md, open question 2), and a unique on athlete_id alone would
     * answer it by accident. */
    uniqueIndex('coach_athlete_relationships_athlete_coach_uniq').on(
      table.athleteId,
      table.coachId,
    ),
  ],
);

// ---------------------------------------------------------------------------
// Messaging
// ---------------------------------------------------------------------------

/** No `created_by` column, which is load-bearing: there is no way to express
 * "I created this conversation" in a query, so POST /conversations owns
 * membership creation rather than the client. */
export const conversations = pgTable('conversations', {
  id: uuid('id').primaryKey().defaultRandom(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  name: text('name'),
  avatarUrl: text('avatar_url'),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const conversationMembers = pgTable(
  'conversation_members',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    conversationId: uuid('conversation_id')
      .notNull()
      .references(() => conversations.id),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id),
    lastReadAt: timestamp('last_read_at', { withTimezone: true }),
  },
  (table) => [
    // "my conversations" is keyed on the member, not the conversation.
    index('conversation_members_user_id_idx').on(table.userId),
    index('conversation_members_conversation_id_idx').on(table.conversationId),
  ],
);

export const messages = pgTable(
  'messages',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    conversationId: uuid('conversation_id')
      .notNull()
      .references(() => conversations.id),
    userId: uuid('user_id').references(() => users.id),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    content: text('content').notNull(),
    /** NOT NULL with no default — every insert must supply it. */
    messageType: messageTypeEnum('message_type').notNull(),
    mediaUrl: text('media_url'),
  },
  (table) => [
    /** Composite, and the column order matters: thread reads filter on
     * conversation_id and sort by created_at (conversations.service.ts:179), so one
     * index serves both and Postgres skips the sort entirely. No DESC here — a
     * B-tree scans backwards just as cheaply. */
    index('messages_conversation_id_created_at_idx').on(table.conversationId, table.createdAt),
  ],
);

// ---------------------------------------------------------------------------
// Exercise library
//
// Both created_by columns reference coaches, not users: only a user with a
// coaches row can author library content.
// ---------------------------------------------------------------------------

export const exercises = pgTable(
  'exercises',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    name: text('name').notNull(),
    createdBy: uuid('created_by')
      .notNull()
      .references(() => coaches.id),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index('exercises_created_by_idx').on(table.createdBy)],
);

export const exerciseTemplates = pgTable(
  'exercise_templates',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    createdBy: uuid('created_by')
      .notNull()
      .references(() => coaches.id),
    name: text('name'),
    exerciseId: uuid('exercise_id')
      .notNull()
      .references(() => exercises.id),
  },
  (table) => [
    index('exercise_templates_created_by_idx').on(table.createdBy),
    index('exercise_templates_exercise_id_idx').on(table.exerciseId),
  ],
);

export const exerciseDefaultSetTemplates = pgTable(
  'exercise_default_set_templates',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    exerciseTemplateId: uuid('exercise_template_id')
      .notNull()
      .references(() => exerciseTemplates.id),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    setNumber: integer('set_number').notNull(),
    prescribedReps: bigint('prescribed_reps', { mode: 'number' }).notNull(),
    prescribedIntensity: text('prescribed_intensity'),
  },
  (table) => [
    index('exercise_default_set_templates_exercise_template_id_idx').on(table.exerciseTemplateId),
  ],
);

// ---------------------------------------------------------------------------
// Programming
// ---------------------------------------------------------------------------

/** athlete_id is nullable and coach_id is not: a workout with no athlete is a
 * template belonging solely to its coach.
 *
 * `is_template` has no default, which is why the template list is currently
 * always empty — createWorkout never wrote the column, so it was NULL, and
 * `.eq('is_template', true)` never matches NULL. Decide the intended semantics
 * when POST /workouts is written. */
export const workouts = pgTable(
  'workouts',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    athleteId: uuid('athlete_id').references(() => athletes.id),
    coachId: uuid('coach_id')
      .notNull()
      .references(() => coaches.id),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    date: date('date').notNull(),
    name: text('name').notNull(),
    notes: text('notes'),
    isTemplate: boolean('is_template'),
  },
  (table) => [
    // An athlete's schedule sorts by date (workouts.service.ts:139); a coach's
    // template list sorts by created_at (workouts.service.ts:160).
    index('workouts_athlete_id_date_idx').on(table.athleteId, table.date),
    index('workouts_coach_id_created_at_idx').on(table.coachId, table.createdAt),
  ],
);

/** `order` is a reserved word in SQL. Drizzle quotes it from the column name
 * string, but any hand-written SQL touching it needs "order". */
export const workoutExercises = pgTable(
  'workout_exercises',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    workoutId: uuid('workout_id')
      .notNull()
      .references(() => workouts.id),
    exerciseId: uuid('exercise_id')
      .notNull()
      .references(() => exercises.id),
    order: integer('order'),
    notes: text('notes'),
    exerciseTemplateId: uuid('exercise_template_id').references(() => exerciseTemplates.id),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    displayName: text('display_name'),
  },
  (table) => [
    // Sorted by "order" on every workout read (workouts.service.ts:71, 182, 386).
    index('workout_exercises_workout_id_order_idx').on(table.workoutId, table.order),
    index('workout_exercises_exercise_id_idx').on(table.exerciseId),
  ],
);

/** Note the asymmetry carried over from the source schema: prescribed_intensity
 * is text but actual_intensity is a double. */
export const sets = pgTable(
  'sets',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    workoutExerciseId: uuid('workout_exercise_id')
      .notNull()
      .references(() => workoutExercises.id),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    setNumber: integer('set_number').notNull(),
    prescribedReps: bigint('prescribed_reps', { mode: 'number' }).notNull(),
    prescribedIntensity: text('prescribed_intensity'),
    suggestedLoadMin: doublePrecision('suggested_load_min'),
    suggestedLoadMax: doublePrecision('suggested_load_max'),
    actualLoad: doublePrecision('actual_load'),
    actualIntensity: doublePrecision('actual_intensity'),
    isCompleted: boolean('is_completed'),
    /** Percentage of the athlete's max for this exercise, when the coach
     * prescribed one. The resolved kg is deliberately NOT stored: it is computed
     * on read against `athlete_maxes`, so refreshing a max re-scales every set
     * prescribed against it. See docs/MAXES-DESIGN.md section 2.3.
     *
     * A set has either this or hand-typed `suggested_load_*`, never both. This
     * wins when present. */
    prescribedPercent: doublePrecision('prescribed_percent'),
  },
  (table) => [
    // Sorted by set_number on every workout read (workouts.service.ts:94, 200).
    index('sets_workout_exercise_id_set_number_idx').on(table.workoutExerciseId, table.setNumber),
  ],
);

// ---------------------------------------------------------------------------
// Maxes
// ---------------------------------------------------------------------------

/** One athlete's max for one exercise, which is what percentage prescription
 * resolves against.
 *
 * **Keyed on `exercise_id`, not on a parent lift, and that is the domain talking
 * rather than a shortcut.** Each squat variation has its own difficulty and
 * therefore its own max — a tempo squat at RPE 7 might be 130kg where a comp squat
 * at RPE 7 is 170kg. Resolving tempo work against a comp squat max would hand the
 * athlete a number wrong by 40kg.
 *
 * The accepted cost: `exercises.created_by` is NOT NULL, so libraries are
 * per-coach, and a coach change leaves the new coach's rows with no history and no
 * derived max. Rare, and an override carries a number across by hand. See
 * docs/MAXES-DESIGN.md section 2.1.
 *
 * **Effective max is `override_value ?? computed_value`.** An override is a pin
 * rather than a seed: it wins until the coach clears it, so a coach who knows the
 * athlete's comp squat is 180 is not overruled by a cautious session.
 */
export const athleteMaxes = pgTable(
  'athlete_maxes',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    athleteId: uuid('athlete_id')
      .notNull()
      .references(() => athletes.id),
    exerciseId: uuid('exercise_id')
      .notNull()
      .references(() => exercises.id),
    /** The coach's pinned number. Wins over anything derived. */
    overrideValue: doublePrecision('override_value'),
    /** Last derived e1RM. Only moves when something asks it to — a max that
     * recomputed on every logged set would move Wednesday's squats because Monday
     * was strong, which is instability rather than autoregulation. */
    computedValue: doublePrecision('computed_value'),
    computedAt: timestamp('computed_at', { withTimezone: true }),
    /** Which set produced `computed_value`. This is what makes the number
     * reviewable: "180kg, from 170x2 @ RPE 8 on 12 Oct" can be argued with, a bare
     * 180 cannot. */
    /** ⚠️ `onDelete: 'set null'` is load-bearing, not decoration. `DELETE
     * /workouts/:id` deletes that workout's sets (workouts.service.ts:706), so
     * without this a coach deleting a workout whose set happened to produce a max
     * gets a foreign-key violation surfaced as a 500. Nulling is also the right
     * semantics: the max is still a valid number, we just can no longer show
     * which set produced it. */
    computedFrom: uuid('computed_from').references(() => sets.id, { onDelete: 'set null' }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index('athlete_maxes_athlete_id_idx').on(table.athleteId),
    /** One row per athlete per exercise. Without this, a refresh racing an override
     * write produces two rows and `?? ` silently picks whichever the query returns
     * first. */
    uniqueIndex('athlete_maxes_athlete_exercise_uniq').on(table.athleteId, table.exerciseId),
  ],
);
