/** Drizzle schema for the LiftOff database.
 *
 * Hand-written from the live Supabase schema captured on 2026-08-03
 * (information_schema.columns + the foreign-key graph + pg_get_viewdef).
 * See docs/DB-SCHEMA.md.
 *
 * NOT generated by `drizzle-kit pull`, deliberately. Introspection would have
 * faithfully carried over the Supabase-isms that must NOT come with us:
 *
 *  - `users.id DEFAULT auth.uid()` — auth.uid() is a Supabase function and does
 *    not exist in RDS. Ids now come from the verified JWT `sub`.
 *  - `users.email NOT NULL` with nothing in the app writing it — a trigger on
 *    auth.users populated it at signup. That trigger does not come with us
 *    either, so the API owns row creation on first login.
 *  - `athletes.id` / `coaches.id` had `DEFAULT gen_random_uuid()` despite always
 *    being the user's id. Vestigial and actively misleading; dropped.
 *
 * The five views are NOT modelled here — Drizzle does not do views, and they
 * port unchanged as plain SQL because none of them reference auth.uid().
 * See migration 0001_create_views.sql.
 */

import {
  bigint,
  boolean,
  date,
  doublePrecision,
  integer,
  pgEnum,
  pgTable,
  smallint,
  text,
  timestamp,
  uuid,
} from 'drizzle-orm/pg-core';

// ---------------------------------------------------------------------------
// Enums
//
// The column dump reported these only as USER-DEFINED, so the type names and
// value lists were recovered separately.
// ALL FOUR VERIFIED 2026-08-04 against the live project, read out of the
// PostgREST OpenAPI spec (which enumerates enum-typed columns) rather than
// guessed. The reconstruction was right on three; coach_athlete_relationship_status
// had a speculative 'inactive' that does not exist and has been removed.
// ---------------------------------------------------------------------------

export const genderEnum = pgEnum('gender', ['Male', 'Female', 'Gender-fluid']);

export const coachRequestStatusEnum = pgEnum('coach_request_status', [
  'pending',
  'accepted',
  'rejected',
]);

export const coachAthleteRelationshipStatusEnum = pgEnum('coach_athlete_relationship_status', [
  'pending',
  'active',
]);

export const messageTypeEnum = pgEnum('message_type', ['text', 'image', 'video', 'file']);

// ---------------------------------------------------------------------------
// Identity
// ---------------------------------------------------------------------------

/** The profile row. One per Supabase auth user.
 *
 * `id` matches the Supabase `auth.users.id` but there is no longer a foreign key
 * to it — auth lives in a different database now. Nothing at the database level
 * prevents an orphaned profile; the API is responsible for creating this row on
 * first login and for not leaving strays behind.
 */
export const users = pgTable('users', {
  id: uuid('id').primaryKey(),
  username: text('username').unique(),
  email: text('email').notNull(),
  gender: genderEnum('gender'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  dateOfBirth: date('date_of_birth'),
  firstName: text('first_name'),
  lastName: text('last_name'),
  isAthlete: boolean('is_athlete'),
  isCoach: boolean('is_coach'),
  avatarUrl: text('avatar_url'),
});

/** Placeholder for unbuilt team features. Two columns, no rows written by
 * anything. Carried over only because athletes.team_id references it. */
export const teams = pgTable('teams', {
  id: uuid('id').primaryKey(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const federations = pgTable('federations', {
  id: uuid('id').primaryKey().defaultRandom(),
  code: text('code').notNull(),
  name: text('name'),
});

export const divisions = pgTable('divisions', {
  id: uuid('id').primaryKey().defaultRandom(),
  federationId: uuid('federation_id')
    .notNull()
    .references(() => federations.id),
  name: text('name'),
  minimumAge: integer('minimum_age'),
  maximumAge: integer('maximum_age'),
});

export const weightClasses = pgTable('weight_classes', {
  id: uuid('id').primaryKey().defaultRandom(),
  federationId: uuid('federation_id')
    .notNull()
    .references(() => federations.id),
  gender: genderEnum('gender'),
  name: text('name'),
  minWeight: doublePrecision('min_weight'),
  maxWeight: doublePrecision('max_weight'),
  sortOrder: smallint('sort_order'),
  active: boolean('active'),
});

/** `id` is both primary key and foreign key to users — athlete id IS user id. */
export const athletes = pgTable('athletes', {
  id: uuid('id')
    .primaryKey()
    .references(() => users.id),
  federationId: uuid('federation_id').references(() => federations.id),
  divisionId: uuid('division_id').references(() => divisions.id),
  weightClassId: uuid('weight_class_id').references(() => weightClasses.id),
  teamId: uuid('team_id').references(() => teams.id),
});

export const coaches = pgTable('coaches', {
  id: uuid('id')
    .primaryKey()
    .references(() => users.id),
  biography: text('biography'),
  yearsOfExperience: integer('years_of_experience'),
});

// ---------------------------------------------------------------------------
// Coach <-> athlete
// ---------------------------------------------------------------------------

export const coachRequests = pgTable('coach_requests', {
  id: uuid('id').primaryKey().defaultRandom(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }),
  athleteId: uuid('athlete_id')
    .notNull()
    .references(() => athletes.id),
  coachId: uuid('coach_id')
    .notNull()
    .references(() => coaches.id),
  status: coachRequestStatusEnum('status').default('pending'),
});

export const coachAthleteRelationships = pgTable('coach_athlete_relationships', {
  id: uuid('id').primaryKey().defaultRandom(),
  athleteId: uuid('athlete_id')
    .notNull()
    .references(() => athletes.id),
  coachId: uuid('coach_id')
    .notNull()
    .references(() => coaches.id),
  status: coachAthleteRelationshipStatusEnum('status').notNull().default('pending'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

// ---------------------------------------------------------------------------
// Messaging
// ---------------------------------------------------------------------------

/** No `created_by` column, which is load-bearing: there is no way to express
 * "I created this conversation" in a query, so POST /conversations owns
 * membership creation rather than the client. */
export const conversations = pgTable('conversations', {
  id: uuid('id').primaryKey().defaultRandom(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  name: text('name'),
  avatarUrl: text('avatar_url'),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const conversationMembers = pgTable('conversation_members', {
  id: uuid('id').primaryKey().defaultRandom(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  conversationId: uuid('conversation_id')
    .notNull()
    .references(() => conversations.id),
  userId: uuid('user_id')
    .notNull()
    .references(() => users.id),
  lastReadAt: timestamp('last_read_at', { withTimezone: true }),
});

export const messages = pgTable('messages', {
  id: uuid('id').primaryKey().defaultRandom(),
  conversationId: uuid('conversation_id')
    .notNull()
    .references(() => conversations.id),
  userId: uuid('user_id').references(() => users.id),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  content: text('content').notNull(),
  /** NOT NULL with no default — every insert must supply it. */
  messageType: messageTypeEnum('message_type').notNull(),
  mediaUrl: text('media_url'),
});

// ---------------------------------------------------------------------------
// Exercise library
//
// Both created_by columns reference coaches, not users: only a user with a
// coaches row can author library content.
// ---------------------------------------------------------------------------

export const exercises = pgTable('exercises', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(),
  createdBy: uuid('created_by')
    .notNull()
    .references(() => coaches.id),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const exerciseTemplates = pgTable('exercise_templates', {
  id: uuid('id').primaryKey().defaultRandom(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  createdBy: uuid('created_by')
    .notNull()
    .references(() => coaches.id),
  name: text('name'),
  exerciseId: uuid('exercise_id')
    .notNull()
    .references(() => exercises.id),
});

export const exerciseDefaultSetTemplates = pgTable('exercise_default_set_templates', {
  id: uuid('id').primaryKey().defaultRandom(),
  exerciseTemplateId: uuid('exercise_template_id')
    .notNull()
    .references(() => exerciseTemplates.id),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  setNumber: integer('set_number').notNull(),
  prescribedReps: bigint('prescribed_reps', { mode: 'number' }).notNull(),
  prescribedIntensity: text('prescribed_intensity'),
});

// ---------------------------------------------------------------------------
// Programming
// ---------------------------------------------------------------------------

/** athlete_id is nullable and coach_id is not: a workout with no athlete is a
 * template belonging solely to its coach.
 *
 * `is_template` has no default, which is why the template list is currently
 * always empty — createWorkout never wrote the column, so it was NULL, and
 * `.eq('is_template', true)` never matches NULL. Decide the intended semantics
 * when POST /workouts is written. */
export const workouts = pgTable('workouts', {
  id: uuid('id').primaryKey().defaultRandom(),
  athleteId: uuid('athlete_id').references(() => athletes.id),
  coachId: uuid('coach_id')
    .notNull()
    .references(() => coaches.id),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  date: date('date').notNull(),
  name: text('name').notNull(),
  notes: text('notes'),
  isTemplate: boolean('is_template'),
});

/** `order` is a reserved word in SQL. Drizzle quotes it from the column name
 * string, but any hand-written SQL touching it needs "order". */
export const workoutExercises = pgTable('workout_exercises', {
  id: uuid('id').primaryKey().defaultRandom(),
  workoutId: uuid('workout_id')
    .notNull()
    .references(() => workouts.id),
  exerciseId: uuid('exercise_id')
    .notNull()
    .references(() => exercises.id),
  order: integer('order'),
  notes: text('notes'),
  exerciseTemplateId: uuid('exercise_template_id').references(() => exerciseTemplates.id),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  displayName: text('display_name'),
});

/** Note the asymmetry carried over from the source schema: prescribed_intensity
 * is text but actual_intensity is a double. */
export const sets = pgTable('sets', {
  id: uuid('id').primaryKey().defaultRandom(),
  workoutExerciseId: uuid('workout_exercise_id')
    .notNull()
    .references(() => workoutExercises.id),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  setNumber: integer('set_number').notNull(),
  prescribedReps: bigint('prescribed_reps', { mode: 'number' }).notNull(),
  prescribedIntensity: text('prescribed_intensity'),
  suggestedLoadMin: doublePrecision('suggested_load_min'),
  suggestedLoadMax: doublePrecision('suggested_load_max'),
  actualLoad: doublePrecision('actual_load'),
  actualIntensity: doublePrecision('actual_intensity'),
  isCompleted: boolean('is_completed'),
});
